### ISSUE TITLE
Also clear files submitted per userforms?

### ISSUE THREAD

**Issue by lerni** [hamaka/userforms-cleanupsubmissions#2]
Just had request to remove files submitted per userforms:
https://gist.github.com/lerni/ee82fbf5b6c5b52bb8025b150b427e74

Would you be interested to integrate something like this in `hamaka/userforms-cleanupsubmissions`? It's deletes files regardless how they are uploaded (userforms or assets/admin), so it's a bit dangerous:warning: Probable the functionality should be hidden/enabled with a config flag.

**Comment by baukezwaan** [comment]
The uploaded files per submission are already cleaned up with the current task. The deleting of the complete userform-folder seems a bit out-of-scope for this task, and not a very common scenario (in my opinion).

Then again; you díd get the question, so there might be a niche market for this feature...
If your comment gets 5 likes, I'll put it in 😎

**Comment by lerni** [comment]
Oh ...->removeAll() indeed removes files already, nevermind.
